export const abi = [
  {
    "type":"function",
    "name":"requestRandomNumber",
    "inputs":[],
    "outputs":[],
    "stateMutability":"payable"
  },
  {"type":"event",
    "name":"RandomnessRequested",
    "inputs":[
      {
        "name":"sequenceNumber",
        "type":"uint64",
        "indexed":false,
        "internalType":"uint64"
      }
    ],
    "anonymous":false
  },
  {
    "type":"event",
    "name":"RandomnessResult",
    "inputs":
    [
      {
        "name":"sequenceNumber",
        "type":"uint64",
        "indexed":false,
        "internalType":"uint64"
      },
      {
        "name":"randomNumber",
        "type":"uint256",
        "indexed":false,
        "internalType":"uint256"
      }
    ],
    "anonymous":false
  }
] as const;